### ISSUE TITLE
I can't run the example in worker.

### ISSUE THREAD

**Issue by thapecroth** [subhendukundu/vitedge-react-template#1]
Hi I try to deploy your example
by install all node_modules and yarn publish.
https://vitedge.thapecroth.workers.dev
The css and all other assets aren't load. Is there any recommendation?

Additionally, do you happen to have an example with a tailwind?

**Comment by subhendukundu** [comment]
What is the error you are seeing while deploying? If any.

**Comment by thapecroth** [comment]
Hi
Thanks for the quick response.
All the css isn't loaded. It's doesn't work in preview mode too. 
I think it's because of the path of the file? 
![image](https://user-images.githubusercontent.com/11730486/116991601-fb235700-acfe-11eb-891e-0280a5601167.png)

**Comment by subhendukundu** [comment]
Umm interesting!
Let's debug. Can you run `npm run dev:ssr`? And see if its running?

**Comment by thapecroth** [comment]
Yes, with all of the css.

**Comment by subhendukundu** [comment]
Good!
How are you deploying it?

**Comment by thapecroth** [comment]
I just add the account_id in wrangler.toml. Then cd back to the main folder and run yarn deploy.
I tried yarn preview, yarn serve:worker, both have same problems.

**Comment by subhendukundu** [comment]
Umm no! That's would work here. We are using Vitedge.
So for local use `npm run dev:ssr`
And for deploying `npm run build` then `npm run deploy`

**Comment by thapecroth** [comment]
Ohh does this mean we don't generate the ssr in the worker?
I try running npm run build then npm run deploy. Still got the same problem css not loaded.

**Comment by subhendukundu** [comment]
So Vitedge takes care of the ssr. Internally they use vitejs.
Are you running it on the root level?

**Comment by thapecroth** [comment]
Yes
You can't replicate my problems?

**Comment by subhendukundu** [comment]
Umm, I was running a wrong repo.  My bad. Yes, I can replicate. I will take a look in a bit what's going wrong.

**Comment by thapecroth** [comment]
Thanks, sorry I can't offer any more insight to help troubleshoot the problem.
